import{mapPlaces}from'./places.js';
export const POI_LABELS=['Transporte','Estación','Bus','Comida','Supermercado','Compras','Farmacia','Café','Mirador/Foto','Interés','Otros'];
export function distanceMeters(a,b){const rad=v=>v*Math.PI/180,dlat=rad(b.lat-a.lat),dlng=rad(b.lng-a.lng),h=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
export const distanceLabel=m=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`;
export const optionalPlace=p=>Boolean(p.poi);
export function nearbyPlaces(places,position){if(!position)return[];const sorted=places.map(p=>({...p,distance:distanceMeters(position,p.gps)})).sort((a,b)=>a.distance-b.distance);const radius=[1000,3000,10000,25000].find(r=>sorted.filter(p=>p.distance<=r).length>=3)||25000;return sorted.filter(p=>p.distance<=radius);}
export function combinedPlaces(events,records,day=null){const pois=records.filter(r=>r.kind==='places_of_interest'&&!r.deleted_at&&(!day||(r.data.assigned_dates||[]).includes(day))).filter(r=>Number.isFinite(r.data.lat)&&Number.isFinite(r.data.lng)).map(r=>({...r.data,id:r.id,poi:true,title:r.data.name,label:{name:r.data.label},gps:{lat:r.data.lat,lng:r.data.lng},start:r.data.assigned_dates?.[0]||'',location:r.data.resolved_address||r.data.name}));return[...mapPlaces(events,day),...pois];}
export function poiKey(p){return p.google_place_id?'place:'+p.google_place_id:Number.isFinite(p.lat)&&Number.isFinite(p.lng)?`${p.lat.toFixed(6)},${p.lng.toFixed(6)}:${String(p.name).trim().replace(/\s+/g,' ').toLowerCase()}`:null;}
export function parsePlacesJson(text){let data;try{data=JSON.parse(text);}catch{throw Error('El JSON no es válido.');}if(!Array.isArray(data.places)||!data.places.length||data.places.length>100)throw Error('Incluye entre 1 y 100 lugares en places.');return data.places.map(p=>{if(!p||typeof p.name!=='string'||!p.name.trim()||typeof p.google_maps_url!=='string')throw Error('Cada lugar necesita nombre y enlace Google Maps.');return{name:p.name.trim().slice(0,250),google_maps_url:p.google_maps_url,description:String(p.description||'').slice(0,4000),label:String(p.label||'Interés').slice(0,100),importance:'optional',priority:p.importance==='Importante'||p.priority==='important'?'important':p.priority==='reference'||p.importance==='Referencia'?'reference':'normal',assignment_mode:p.assignment==='manual'?'manual':'auto',assigned_dates:Array.isArray(p.assigned_dates)?p.assigned_dates:[],assigned_areas:Array.isArray(p.assigned_areas)?p.assigned_areas:[],visited:false};});}
export function assignPlace(place,events){if(place.assignment_mode==='manual')return place;const close=mapPlaces(events).filter(e=>distanceMeters(place,e.gps)<=25000);return{...place,assigned_dates:[...new Set(close.map(e=>e.start.slice(0,10)))],assigned_areas:place.resolved_city?[place.resolved_city]:[]};}
